### PR TITLE
refactor: create folder for button.stories (#58)

### PR DESCRIPTION
**Pull request by noviceCoder27**
Created a folder called chip for the button.stories.tsx file.

### CODE REVIEW

**Comment by iurynogueira** [comment]
@noviceCoder27 thks for your contribute, please change folder name to button.

**Comment by noviceCoder27** [comment]
Since its my first time contributing to a project I might have done some mistake at the end. If there's any problem I'd like you to mention it so that I can correct myself.

**Comment by iurynogueira** [comment]
> Since its my first time contributing to a project I might have done some mistake at the end. If there's any problem I'd like you to mention it so that I can correct myself.

No problem, thanks for your contribution, I hope to see news contributions by you again, we can help you with anythink.

**Comment by noviceCoder27** [comment]
> > Since its my first time contributing to a project I might have done some mistake at the end. If there's any problem I'd like you to mention it so that I can correct myself.
> 
> No problem, thanks for your contribution, I hope to see news contributions by you again, we can help you with anythink.

Yeah I'll try to contribute on the things I can

**Pull request merged**
